---
- name: update grub
  ansible.builtin.command: update-grub
  register: output
  changed_when: output.rc == 0
  when:
    - not ansible_is_chroot

- name: restart sshd
  ansible.builtin.systemd:
    name: sshd
    state: restarted

- name: restart auditd
  ansible.builtin.systemd:
    name: auditd
    state: restarted

- name: restart rsyslog
  ansible.builtin.systemd:
    name: rsyslog
    state: restarted

- name: reboot system
  ansible.builtin.reboot:
    msg: "Rebooting Machine"
