# VM variables
var_isolation_tools_copy_disable: 'true'
var_isolation_tools_dnd_disable: 'true'
var_isolation_tools_paste_disable: 'true'
var_isolation_tools_diskshrink_disable: 'true'
var_isolation_tools_diskwiper_disable: 'true'
var_isolation_tools_hgfs_disable: 'true'
var_remote_display_max_connections: '1'
var_remote_vnc_enabled: 'false'
var_tools_setinto_sizelimit: '1048576'
var_isolation_device_connectable_disable: 'true'
var_tools_guestlib_enablehostinfo: 'false'
var_tools_guest_desktop_autolock: 'true'
var_mks_enable3d: 'false'
var_log_rotatesize: '2048000'
var_log_keepold: '10'