galaxy_info:
  author: Broadcom
  description: VMware Cloud Foundation SDDC Manager Appliance PostgreSQL Service STIG Readiness Guide Role
  company: Broadcom
  license: Apache
  min_ansible_version: '2.9'
  galaxy_tags:
    - stig
    - vmware
    - vcf
    - sddcmgr
    - postgresql
