---

# Turn specific controls on/off by setting the value to true or false

#VCSA-70-000023
run_vim_pass_expiration_days: true
#VCSA-70-000024
run_vpxd_host_pass_length: true
#VCSA-70-000036
run_log_level: true
#VCSA-70-000075
run_vpxd_event_syslog_enabled: true
#VCSA-70-000078
run_db_retention: true