# VMware vSphere 7.0 vCenter Ansible Role

---

 #---------- Ansible version 2.10 --------#

############################################

- name: VCSA-70-000023 - The vCenter Server must configure the vpxuser auto-password to be changed every 30 days.
  community.vmware.vmware_vcenter_settings:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    validate_certs: '{{ validate_certs }}'
    advanced_settings:
      'VirtualCenter.VimPasswordExpirationInDays': '{{ var_vim_pass_expiration_days }}'
  delegate_to: localhost
  tags:
  - VCSA-70-000023
  when:
  - run_vim_pass_expiration_days | bool

############################################

- name: VCSA-70-000024 - The vCenter Server must configure the vpxuser password meets length policy.
  community.vmware.vmware_vcenter_settings:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    validate_certs: '{{ validate_certs }}'
    advanced_settings:
      'config.vpxd.hostPasswordLength': '{{ var_vpxd_host_pass_length }}'
  delegate_to: localhost
  tags:
  - VCSA-70-000024
  when:
  - run_vpxd_host_pass_length | bool

############################################

- name: VCSA-70-000036 - The vCenter Server must produce audit records containing information to establish what type of events occurred.
  community.vmware.vmware_vcenter_settings:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    validate_certs: '{{ validate_certs }}'
    advanced_settings:
      'config.log.level': '{{ var_log_level }}'
  delegate_to: localhost
  tags:
  - VCSA-70-000036
  when:
  - run_log_level | bool

############################################

- name: VCSA-70-000075 - The vCenter server must be configured to send events to a central log server.
  community.vmware.vmware_vcenter_settings:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    validate_certs: '{{ validate_certs }}'
    advanced_settings:
      'vpxd.event.syslog.enabled': '{{ var_vpxd_event_syslog_enabled }}'
  delegate_to: localhost
  tags:
  - VCSA-70-000075
  when:
  - run_vpxd_event_syslog_enabled | bool

############################################

- name: VCSA-70-000078 - vCenter task and event retention must be set to at least 30 days.
  community.vmware.vmware_vcenter_settings:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    validate_certs: '{{ validate_certs }}'
    database:
      event_retention: '{{ var_db_event_retention }}'
      task_retention: '{{ var_db_task_retention }}'
  delegate_to: localhost
  tags:
  - VCSA-70-000078
  when:
  - run_db_retention | bool